<x-layouts.admin
    title="RFP inbox"
    subtitle="Enquiries from the Request for Proposal form. This is the only table whose contents cannot be regenerated by re-seeding, so back it up."
>
    <div class="adm__panel">
        <div class="adm__panelhead">
            <div><h2>{{ $submissions->total() }} enquir{{ $submissions->total() === 1 ? 'y' : 'ies' }}</h2></div>
            @php $unack = $submissions->getCollection()->whereNull('acknowledged_at')->count(); @endphp
            @if ($unack)
                <span class="pill pill--blocking">{{ $unack }} unacknowledged on this page</span>
            @endif
        </div>

        @forelse ($submissions as $submission)
            <div class="adm__row">
                <div class="adm__rowhead">
                    <a class="adm__rowtitle" href="{{ route('admin.rfp.show', $submission) }}">{{ $submission->organisation }}</a>
                    <span class="pill pill--muted">{{ $submission->track->label() }}</span>
                    @if ($submission->nda_required)
                        <span class="pill pill--open">NDA requested</span>
                    @endif
                    @if ($submission->acknowledged_at)
                        <span class="pill pill--closed">Acknowledged</span>
                    @else
                        <span class="pill pill--blocking">Awaiting reply</span>
                    @endif
                </div>
                <p style="margin:0 0 .5rem;font-size:.85rem;color:var(--ink-2)">
                    {{ Str::limit($submission->scope_summary, 180) }}
                </p>
                <p style="margin:0;font-size:.78rem;color:var(--muted)">
                    {{ $submission->reference }} &middot; {{ $submission->contact_name }}
                    &lt;{{ $submission->email }}&gt; &middot; {{ $submission->created_at->format('j M Y, H:i') }}
                </p>
            </div>
        @empty
            <p class="adm__empty">No enquiries yet.</p>
        @endforelse
    </div>

    {{ $submissions->links() }}
</x-layouts.admin>
